package com.seckill.dao;

import java.util.List;

import com.seckill.models.Item;

public interface ItemMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item
   *
   * @mbg.generated Sun Jan 19 21:06:04 GMT 2020
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item
   *
   * @mbg.generated Sun Jan 19 21:06:04 GMT 2020
   */
  int insert(Item record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item
   *
   * @mbg.generated Sun Jan 19 21:06:04 GMT 2020
   */
  int insertSelective(Item record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item
   *
   * @mbg.generated Sun Jan 19 21:06:04 GMT 2020
   */
  Item selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item
   *
   * @mbg.generated Sun Jan 19 21:06:04 GMT 2020
   */
  int updateByPrimaryKeySelective(Item record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table item
   *
   * @mbg.generated Sun Jan 19 21:06:04 GMT 2020
   */
  int updateByPrimaryKey(Item record);

  List<Item> selectAll();
}