package com.seckill.dao;

import com.seckill.models.Promo;

public interface PromoMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table promo
   *
   * @mbg.generated Sun Jan 26 13:22:05 GMT 2020
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table promo
   *
   * @mbg.generated Sun Jan 26 13:22:05 GMT 2020
   */
  int insert(Promo record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table promo
   *
   * @mbg.generated Sun Jan 26 13:22:05 GMT 2020
   */
  int insertSelective(Promo record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table promo
   *
   * @mbg.generated Sun Jan 26 13:22:05 GMT 2020
   */
  Promo selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table promo
   *
   * @mbg.generated Sun Jan 26 13:22:05 GMT 2020
   */
  int updateByPrimaryKeySelective(Promo record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table promo
   *
   * @mbg.generated Sun Jan 26 13:22:05 GMT 2020
   */
  int updateByPrimaryKey(Promo record);

  Promo selectByItemId(Integer itemId);
}