package com.seckill.dao;

import com.seckill.models.SequenceInfo;

public interface SequenceInfoMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sequence_info
   *
   * @mbg.generated Sun Jan 26 12:39:38 GMT 2020
   */
  int deleteByPrimaryKey(String name);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sequence_info
   *
   * @mbg.generated Sun Jan 26 12:39:38 GMT 2020
   */
  int insert(SequenceInfo record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sequence_info
   *
   * @mbg.generated Sun Jan 26 12:39:38 GMT 2020
   */
  int insertSelective(SequenceInfo record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sequence_info
   *
   * @mbg.generated Sun Jan 26 12:39:38 GMT 2020
   */
  SequenceInfo selectByPrimaryKey(String name);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sequence_info
   *
   * @mbg.generated Sun Jan 26 12:39:38 GMT 2020
   */
  int updateByPrimaryKeySelective(SequenceInfo record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sequence_info
   *
   * @mbg.generated Sun Jan 26 12:39:38 GMT 2020
   */
  int updateByPrimaryKey(SequenceInfo record);

  SequenceInfo getSequenceByName(String name);
}