package com.seckill.dao;

import org.apache.ibatis.annotations.Param;

import com.seckill.models.Stock;

public interface StockMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table stock
   *
   * @mbg.generated Sun Jan 19 21:06:04 GMT 2020
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table stock
   *
   * @mbg.generated Sun Jan 19 21:06:04 GMT 2020
   */
  int insert(Stock record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table stock
   *
   * @mbg.generated Sun Jan 19 21:06:04 GMT 2020
   */
  int insertSelective(Stock record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table stock
   *
   * @mbg.generated Sun Jan 19 21:06:04 GMT 2020
   */
  Stock selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table stock
   *
   * @mbg.generated Sun Jan 19 21:06:04 GMT 2020
   */
  int updateByPrimaryKeySelective(Stock record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table stock
   *
   * @mbg.generated Sun Jan 19 21:06:04 GMT 2020
   */
  int updateByPrimaryKey(Stock record);

  Stock selectByItemId(Integer itemId);

  int reduceStock(@Param("itemId") Integer itemId, @Param("amount") Integer amount);
}