server:
  port: 8081
  # optimize tomcat
  tomcat:
    accept-count: 1000
    max-threads: 800 # 4 core 8GB RAM server
    min-spare-threads: 100
    accesslog:
      enabled: true
      directory: /var/www/seckill/tomcat
      pattern: %h %l %u %t %r %s %b %D

mybatis:
  mapperLocations: classpath:mapping/*.xml
  
spring:
  datasource:
    name: seckill
    url: jdbc:mysql://localhost:3306/seckill
    username: root
    password: lizhimysql
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    database: 10
    port: 6379
    #password
    jedis:
      pool:
        max-active: 50
        min-idle: 20

mq:
  nameserver:
    addr: 47.105.202.224:9876
  topicname: stock
